### ISSUE TITLE
[BUG] Shulker box disappears when put in player inventory crafting grid

### ISSUE THREAD

**Issue by RedSparr0w** [tryashtar/shulker-preview#1]
**Minecraft Version:**
`20w15a`

**Bug:**
Shulker box disappears when put in player inventory crafting grid.

**Steps to reproduce:**
1. Place items in shulker box
2. Pickup shulker box
3. Open inventory
4. Place in player crafting grid
5. Shulker box disappears

**Notes:**
The shulker box will not disappear when used in standard crafting table.
It also will not disappear if it is empty.

**Comment by tryashtar** [comment]
This is a vanilla bug: https://bugs.mojang.com/browse/MC-172272

Since it only affects the snapshots, I will not implement a workaround unless 1.16 releases with this bug still unfixed (unlikely to happen).

**Comment by RedSparr0w** [comment]
Okay cool, I’ll leave the issue open Incase anyone else encounters it too.
And then close once the issue is fixed on Minecrafts side.
