### ISSUE TITLE
Datapack not working

### ISSUE THREAD

**Issue by Vlame04** [tryashtar/shulker-preview#12]
I play on Minecraft Badlion 1.16.4.

If I enable the datapack and disable the resource pack, it shows the normal vanilla shulkers. If I have enabled the resource pack, I get a weird unicode code (see image)

Can anyone help me with this?

![image_2020-12-31_161146](http://vlamefotootjes.tk/fotootjes/67mu2lih.png)

**Comment by tryashtar** [comment]
Does it work using the vanilla client? I can't guarantee support with mods, and I would test it myself on badlion but am really not comfortable tying my MC account to their system

**Comment by Vlame04** [comment]
I works using the vanilla client. Not with the Badlion. That was the problem
