### ISSUE TITLE
Dark Mode for Resource Pack

### ISSUE THREAD

**Issue by NEODyst** [tryashtar/shulker-preview#14]
Well the title says it

Can you make a dark mode version of the resource pack? Having trouble trying to modify the original one
Also maybe smooth font?

**Comment by tryashtar** [comment]
It should be pretty easy, the only files to replace are these:
* [textures/shulker_tooltip.png](https://github.com/tryashtar/shulker-preview/blob/1.17/resourcepack/assets/tryashtar.shulker_preview/textures/shulker_tooltip.png)
* [textures/shulker_tooltip_header.png](https://github.com/tryashtar/shulker-preview/blob/1.17/resourcepack/assets/tryashtar.shulker_preview/textures/shulker_tooltip_header.png)
* [textures/ender_tooltip.png](https://github.com/tryashtar/shulker-preview/blob/1.17/resourcepack/assets/tryashtar.shulker_preview/textures/ender_tooltip.png)
