### ISSUE TITLE
Missing Textures for Crossbows Loaded with Tipped and Spectral Arrows

### ISSUE THREAD

**Issue by Arcosh** [tryashtar/shulker-preview#16]
Crossbows loaded with any tipped arrows (e.g. "Instant Health 2") or a spectral arrow are missing a texture

Image:
The arrow **below** the crossbow is what is loaded into it.

![crossbows_tipped_arrows_bug](https://user-images.githubusercontent.com/93728567/145632807-8cdae132-7900-45e5-a3a8-8965ad816f3c.jpg)

*Note: There also appears to be some glitch with the damage bar appearing lower than it should be, but that is also present when a normal arrow is loaded in the crossbow.

**Comment by tryashtar** [comment]
Nice catch! Fixed both for 1.18. Both issues were in the data pack so only need to re-download that:
https://github.com/tryashtar/shulker-preview/raw/1.18/Shulker%20Preview%20Data%20Pack%20(1.18).zip
