### ISSUE TITLE
[1.19] Sculk names are incorrectly displayed

### ISSUE THREAD

**Issue by isuke01** [tryashtar/shulker-preview#24]
Hi,

I noticed in 1.19 version. Vanilia server and this is only Datapack that we have the new items from 1.19 are bugged. The names are transalted to suare symbols. 
Screenshot below how it looks.

![image](https://user-images.githubusercontent.com/12289763/176932296-738c6ba1-ca10-4707-897c-224ee5f7c93c.png)

**Comment by tryashtar** [comment]
Please try with the latest version, and let me know if this still happens
