### ISSUE TITLE
For some reason it just stopped working.

### ISSUE THREAD

**Issue by DenisakeRO** [tryashtar/shulker-preview#25]
sooo,ur datapack+texture pack worked for me but today they just stopped,im plaing on 1.18.2 and the shulkers and interior of ender chests say:[][][][][][] [][] [] [][][] [][]-[][] [][][][][] [] [][] in purple text color. Do you know why this happen?
My only theory is that this only works on forge?Cause now im playing on fabric bc i am using a fps boost modpack,maybe thats the cause?

Thanks for reading my good sir
![whyme](https://user-images.githubusercontent.com/108822565/177595187-46ef5ae1-c0b0-4b73-bf75-0b1074c9d4c5.png)

**Comment by tryashtar** [comment]
Please try with the latest version, and let me know if this still happens
