### ISSUE TITLE
Shulker Preview when shulker is named

### ISSUE THREAD

**Issue by D3v1lPho3n1x** [tryashtar/shulker-preview#27]
When I renamed the shulker box. Everything shifted slightly
![2022-09-02_12 21 08](https://user-images.githubusercontent.com/112718102/188196924-050ca8d5-89dc-4556-8eaf-9c56d3a65d2c.png)

**Comment by Rohan-511** [comment]
Whrer did you get the dark theme preview from?

**Comment by D3v1lPho3n1x** [comment]
Ur website

**Comment by Rohan-511** [comment]
Sorry didn't get that

**Comment by D3v1lPho3n1x** [comment]
I got it from the website

**Comment by tryashtar** [comment]
Please try with the latest version, and let me know if this still happens
