### ISSUE TITLE
Some blocks have white pixels where they shouldn't have

### ISSUE THREAD

**Issue by ValkWetenschap** [tryashtar/shulker-preview#28]
I've noticed that some textures show up with random white pixels where they shouldn't and I haven't found a solution. Although the Image below is of an ender chest full of shulker boxes I've noticed that it happens regardless of the container or the type of block. My assumption is that there is an issue with the block_sheet.png file or how it is being read into the datapack.
![Screenshot_20230103_120511](https://user-images.githubusercontent.com/70231194/210424880-4faa9982-74b8-43ec-8d0a-63132ed6462b.png)

**Comment by ValkWetenschap** [comment]
I'm in 1.19.3 btw. Not sure if that matters or not.

**Comment by ValkWetenschap** [comment]
Update: turns out it was a conflict with another resource pack. Not sure what causes it though

**Comment by tryashtar** [comment]
That's interesting, would you mind uploading or linking to the pack you found to be causing the problem?

**Comment by ValkWetenschap** [comment]
Well, it's Vanilla Tweaks so I'm not sure how helpful that will be. [https://vanillatweaks.net/picker/resource-packs/](url)
[MyVanillaTweaks_V9.zip](https://github.com/tryashtar/shulker-preview/files/10339578/MyVanillaTweaks_V9.zip)

**Comment by tryashtar** [comment]
Thanks! I looked into it and pinpointed the issue:
The `DarkUI1193` module overrides the vanilla `rendertype_text.fsh` shader, adding this line:
```
if (vertexDistance > 800.0 && color.r > 0.2479 && color.r < 0.2481) color = vec4(1.0, 1.0, 1.0, 1.0);
```
This seems to be a misguided attempt at making text in UIs white to provide better contrast. There is no non-destructive way for me to fix this on my end; I recommend that whoever made that module improve their implementation of that feature.

**Comment by ValkWetenschap** [comment]
Do you know of a less problematic way of changing text color?

**Comment by tryashtar** [comment]
I don't know enough about shaders to know if the desired text can be pinpointed exactly, but checking the color more precisely instead of just the R component would be an obvious improvement.
I also don't really see much wrong with the old way of just putting `§f` in the translation
