### ISSUE TITLE
Unable to enable ender chest viewing 

### ISSUE THREAD

**Issue by ArrowSwift509** [tryashtar/shulker-preview#31]
So I recently downloaded the shulker preview data pack and resource pack for a survival world of mine. It works great for the shulker boxes. Unfortunately, when I try to enable ender chests using the command on the github.io page (/function tryashtar.shulker_preview:config/show_settings) I get the error that is shown in the screenshot below. I figured maybe I just couldn't paste it in. But typing it in by hand showed that the command is not even available for auto fill (I assume that's the right terminology) Not sure whats going on here.
![Shulker Preview Issue](https://github.com/tryashtar/shulker-preview/assets/85365323/943b0d10-ab4f-4c97-adfe-fd83cb68cba5)
![Shulker Preview Issue 2](https://github.com/tryashtar/shulker-preview/assets/85365323/42cdf692-3b5c-4f39-89d9-b8c024a78083)

**Comment by ArrowSwift509** [comment]
One other thing that I forgot to put in the main post. This is a world that I share with my brothers but it is hosted on my computer and I am the creator and owner of the world. Not sure if that would make a difference but I figured I'd mention it just in case

**Comment by tryashtar** [comment]
Hey there. In order to use that command, you'll need to have cheats on. You might be able to just enable them temporarily if that works for you

**Comment by ArrowSwift509** [comment]
Awesome that worked! Really appreciate the quick response. Thanks!
