### ISSUE TITLE
Mismatched Axe and End Chest ID

### ISSUE THREAD

**Issue by SPACED0UBT** [tryashtar/shulker-preview#34]
My axe thinks it's an ender chest. It shows the contents of my ender chest 2 hours ago.

![2024-05-13_19 25 20](https://github.com/tryashtar/shulker-preview/assets/123533119/04b76947-29f8-41ad-8983-b1aceb38aa6b)

**Comment by tryashtar** [comment]
Nice catch, thank you for the report. I've found the issue and just pushed a fix.
To fix any items affected by this, you'll need to hold them in your hand and run this command:
```
/item modify entity @s weapon {function:"set_lore",mode:"replace_all",lore:[]}
```
Sorry for any trouble
