### ISSUE TITLE
(solved) Doesn't change anything

### ISSUE THREAD

**Issue by ClassyCar** [tryashtar/shulker-preview#36]
Hello everyone. I'm on 1.21 and I've just completed the installation steps. I've moved the datapack to my datapacks folder and made sure it was enabled, and then enabled the resource pack. The issue is that once minecraft is done loading from the texturepack applying, nothing has been changed.
![image](https://github.com/tryashtar/shulker-preview/assets/105870385/1d6803f9-11e2-4882-b10b-e8ad1bed3f36)
![image](https://github.com/tryashtar/shulker-preview/assets/105870385/e027613b-c6c2-4d2a-a56c-4df171cedfe4)
![image](https://github.com/tryashtar/shulker-preview/assets/105870385/a784f539-863a-4d9e-9515-bef96ab0e4f5)
Yes, I've tried relaunching. 
Yes, I've tried disabling and re-enabling the resource pack.
The resourcepack in question is at the top of my list.

**Comment by tryashtar** [comment]
It's not clear from that screenshot, do you *just* have the dark theme pack? All it does is remove some textures from the main resource pack, you need it as well.

**Comment by ClassyCar** [comment]
> do you _just_ have the dark theme pack?

That was the issue, I should've noticed the file size discrepancy. Thank you!

![image](https://github.com/tryashtar/shulker-preview/assets/105870385/cdf06674-7a2e-48a2-a18c-2960fc09ef1a)

**Comment by tryashtar** [comment]
Yay, glad you got it working!
