### ISSUE TITLE
Eyes of ender do not show properly

### ISSUE THREAD

**Issue by ClassyCar** [tryashtar/shulker-preview#37]
![image](https://github.com/tryashtar/shulker-preview/assets/105870385/d8f06d16-e5fc-4912-9fc9-f1caa6766768)
![Screenshot 2024-06-30 214012](https://github.com/tryashtar/shulker-preview/assets/105870385/e372c1cd-2c64-4172-9858-86d72f17e6be)

Eyes of ender do not show properly and also mess with the alignment. This happens for ender chests and shulkers. I am using 1.21.
As far as I've gotten in my survival world, that's the only thing that has no icon.

**Comment by tryashtar** [comment]
Nice catch, thank you! It's those pesky arabic characters again! I've pushed a fix to this for both 1.21 and 1.20.5, only the resource pack changed.
