### ISSUE TITLE
Enderchest viewer bug

### ISSUE THREAD

**Issue by kristianzimmermann** [tryashtar/shulker-preview#6]
![image](https://user-images.githubusercontent.com/54281809/85960441-b96da580-b9a3-11ea-9e46-4fbd2b95afe2.png)
I haven't tested this out and tried to get a reliable way of reproducing it (yet), but from playing with it on a survival server. Some of us who put items into an enderchest had the item destroyed and was given TNT with the shulker box viewer effect. We've easily lost multiple items due to this bug, and disabling enderchest viewer seems to have "fixed" it.

**Comment by tryashtar** [comment]
Hey there. My apologies for the item loss, and thanks for the report. Would you mind uploading the data pack you're using here? I thought I had made some changes earlier to prevent this, but I'm not entirely confident.

**Comment by kristianzimmermann** [comment]
https://drive.google.com/file/d/1fwgs21xbsP0Sq08rwpUniSNcCOmaZMQX/view?usp=sharing

Straight from the server

**Comment by tryashtar** [comment]
Ah yep, it looks like you happened to download it during the four hour window where the ender chest system was not secure 😅 

Replace the data pack with this one, and it should not happen again
https://github.com/tryashtar/shulker-preview/raw/1.16/Shulker%20Preview%20Data%20Pack%20(1.16).zip

**Comment by kristianzimmermann** [comment]
Oof, seems like my perfect timing can have some downsides xD
